addpath('../io');
addpath('../preprocess');
addpath('../classify');
addpath('..');

dark = imreads('../../img/Dark/');
flat = imreads('../../img/Flat/');
bias = imreads('../../img/Bias/');
[measurements, fnames] = imreads('../../img/Measurements/');

truth = [1 1 1 1 1 1; ...
         0 0 1 0 1 3; ...
         1 1 5 0 0 1; ...
         3 1 3 0 0 0; ...
         3 1 4 0 1 0; ...
         2 0 1 0 3 0; ...
         0 0 3 0 1 0; ...
         3 0 4 1 0 0; ...
         3 1 0 0 0 0; ...
         0 0 4 1 0 0; ...
         0 0 5 1 3 0; ...
         0 0 1 1 3 0];

n = length(measurements);
total_errors = 0;
for i = 1:n
    I = measurements{i};
    coins = estim_coins(I, dark, flat, bias);
    disp(fnames{i});
    disp(coins);
    err = coins-truth(i, :)
    total_errors = total_errors + sum(abs(err));
end

disp(sum(truth(:)));
disp(total_errors);
