addpath('../io');
addpath('../preprocess');
addpath('../classify');
addpath('..');

bias = imreads('../../img/Bias/');
dark = imreads('../../img/Dark/');
flat = imreads('../../img/Flat/');
[measurements, fnames] = imreads('../../img/Measurements/');

truth = [1 1 1 1 1 1; ...
         0 0 1 0 1 3; ...
         1 1 5 0 0 1; ...
         3 1 3 0 0 0; ...
         3 1 4 0 1 0; ...
         2 0 1 0 3 0; ...
         0 0 3 0 1 0; ...
         3 0 4 1 0 0; ...
         3 1 0 0 0 0; ...
         0 0 4 1 0 0; ...
         0 0 5 1 3 0; ...
         0 0 1 1 3 0];

n = length(measurements);
for i = 1:n
    I = measurements{i};
    coins = estim_coins(I, bias, dark, flat);
    disp(fnames{i});
    disp(coins);
    disp(coins-truth(i, :));
end
